### PR TITLE
Modularize build, migrate to sbt 0.13.1, enable Travis CI

### PR DESCRIPTION
**Pull request by adriaanm**
This makes me wonder, is there a way we can run sbt in "minimal mode", where it only loads build.sbt, but no plugins / other *.sbt files? This would probably be useful for dbuild, if we stick to the convention that the core build defines what's necessary for building/testing/publishing, and the other .sbt files are optional.

review by @jsuereth, @vjovanov

### CODE REVIEW

**Comment by adriaanm** [comment]
(Publishing a new 2.11.0-SNAPSHOT that has the M8 fixes for the cross-version conflict.)

I also haven't tested the gh-pages part of the build as my three attempts at installing jekyll all failed...

**Comment by jsuereth** [comment]
LGTM

**Comment by vjovanov** [comment]
LGTM. 

I could not test the gh-pages as the sbt-site is not working properly for newer versions of jekyll. Something along the lines of this [PR](https://github.com/sbt/sbt-site/pull/40) should fix it.

**Comment by adriaanm** [comment]
Thanks for the prompt review!

**Comment by adriaanm** [comment]
Here's the travis run of the merge of this PR -- hopefully it'll be green :-)

https://travis-ci.org/scala/actors-migration/builds/17577577

**Pull request merged**
